---
title: "RAProject"
author: "Mingzhi Ye"
date: "2022/10/10"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,include = FALSE}
library(VDJdive)
library(tidyverse)
require(SingleCellExperiment)
library(r2r)
library(reticulate)
# Use Python 3.9, require pandas, numpy and scipy
use_python('/usr/local/bin/python3')
#use_virtualenv("/Users/mingzhiye/PycharmProjects/pythonProject/venv")
source_python("./main.py")
```



# Calculate Intermediate Result Table for samples

```{r,message = FALSE,warning = FALSE}
#time0=Sys.time()

getResultTable <- function(PoolSize,SampleSize,Times,BaseNumber=0){
  generateSamplePool(PoolSize)
  
  for(i in 1:Times){
    sample=getSample(PoolSize,SampleSize,BaseNumber)
    
    sample$high_confidence<-as.logical(sample$high_confidence)
    sample$productive<-as.logical(sample$productive)
    sample$full_length<-as.logical(sample$full_length)
    sample$is_cell<-as.logical(sample$is_cell)
    
    samplelist <- split(sample, f = sample$barcode)
    samplelist  <- SplitDataFrameList(samplelist)
    
    EMpredicted <- clonoStats(samplelist, method = 'EM')
    updateMergedDataframe(clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])
  
    UNpredicted <- clonoStats(samplelist, method = 'unique')
    updateMergedDataframe(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1])
    
    
    #print(i)
    #time1=Sys.time()
    #print(time1-time0)
    #time0=time1
    
  
  }
  result=getIntermediateResult(Times)
  clearStorage()
  return(result)
}


#Intermediate=getResultTable(200L,500L,1L)


```

# Calculate distances for samples

```{r,message = FALSE,warning = FALSE}
#time0=Sys.time()

getDistanceDataFrame <- function(PoolSize,SampleSize,Times,BaseNumber=0){
  generateSamplePool(PoolSize)
  DistanceListFromEM=c()
  DistanceListFromUN=c()
  for(i in 1:Times){
    sample=getSample(PoolSize,SampleSize,BaseNumber)
    
    sample$high_confidence<-as.logical(sample$high_confidence)
    sample$productive<-as.logical(sample$productive)
    sample$full_length<-as.logical(sample$full_length)
    sample$is_cell<-as.logical(sample$is_cell)
    
    samplelist <- split(sample, f = sample$barcode)
    samplelist  <- SplitDataFrameList(samplelist)
    
    EMpredicted <- clonoStats(samplelist, method = 'EM')
    DistanceListFromEM[i]=getDistance(clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])
  
    UNpredicted <- clonoStats(samplelist, method = 'unique')
    DistanceListFromUN[i]=getDistance(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1])
    
    
    #print(i)
    #time1=Sys.time()
    #print(time1-time0)
    #time0=time1
    
  
  }

  clearStorage()
  return(data.frame(DistanceListFromUN,DistanceListFromEM))
}


# ResultDistances=getDistanceDataFrame(200L,500L,1L)


```


# Calculate distance, KL Divergence, and JS Divergence for samples

```{r,message = FALSE,warning = FALSE}
#time0=Sys.time()

getEvaluationDataFrame <- function(PoolSize,SampleSize,Times,BaseNumber=0){
  generateSamplePool(PoolSize)
  DistanceListFromEM=c()
  DistanceListFromUN=c()
  KLDivergenceListFromEM=c()
  KLDivergenceListFromUN=c()
  JSDivergenceListFromEM=c()
  JSDivergenceListFromUN=c()
  DistanceListUN_EM=c()
  for(i in 1:Times){
    sample=getSample(PoolSize,SampleSize,BaseNumber)
    
    sample$high_confidence <- as.logical(sample$high_confidence)
    sample$productive<-as.logical(sample$productive)
    sample$full_length<-as.logical(sample$full_length)
    sample$is_cell<-as.logical(sample$is_cell)
    
    samplelist <- split(sample, f = sample$barcode)
    samplelist  <- SplitDataFrameList(samplelist)
    
    EMpredicted <- clonoStats(samplelist, method = 'EM')
    DistanceListFromEM[i]=getDistance(clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])
    KLDivergenceListFromEM[i]=getKLDivergence(clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])
    JSDivergenceListFromEM[i]=getJSDivergence(clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])

    UNpredicted <- clonoStats(samplelist, method = 'unique')
    DistanceListFromUN[i]=getDistance(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1])
    KLDivergenceListFromUN[i]=getKLDivergence(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1])
    JSDivergenceListFromUN[i]=getJSDivergence(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1])
    
    DistanceListUN_EM[i]=getDistanceTwoSamples(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1],clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])

    
    #print(i)
    #time1=Sys.time()
    #print(time1-time0)
    #time0=time1
    
  
  }

  clearStorage()
  return(data.frame(DistanceListFromUN,DistanceListFromEM,KLDivergenceListFromUN,KLDivergenceListFromEM,JSDivergenceListFromUN,JSDivergenceListFromEM,DistanceListUN_EM))
}


ResultDistances=getEvaluationDataFrame(10000L,500L,10L,0.9)


```

# Visualize
```{r}
boxplot(ResultDistances$DistanceListFromEM)
hist(ResultDistances$DistanceListFromEM)
boxplot(ResultDistances$DistanceListFromUN)
hist(ResultDistances$DistanceListFromUN)
print(median(ResultDistances$DistanceListFromEM))
print(median(ResultDistances$DistanceListFromUN))
print(mean(ResultDistances$DistanceListFromEM))
print(mean(ResultDistances$DistanceListFromUN))
print(mean(ResultDistances$JSDivergenceListFromEM))
print(mean(ResultDistances$JSDivergenceListFromUN))
```

```{r, eval=FALSE}
# library(VDJdive)
sample1 <- readVDJcontigs("sample1")
sample2 <- readVDJcontigs("sample2")

EMpredicted1 <- clonoStats(sample1, method = 'EM')
UNpredicted1 <- clonoStats(sample1, method = 'unique')

EMpredicted2 <- clonoStats(sample2, method = 'EM')
UNpredicted2 <- clonoStats(sample2, method = 'unique')
DISTANCE=getDistanceTwoSamples(clonoNames(EMpredicted2),clonoAbundance(EMpredicted2)[,1],clonoNames(UNpredicted2),clonoAbundance(UNpredicted2)[,1])
```


# Compare clonotype distributions from UN and EM methods in real data
```{r}
# Set the root directory
root_dir <- "/Users/mingzhiye/RProjects/RAProgram/samples"

# Recursively list all directories in the root directory
result <- list.dirs(root_dir, recursive = TRUE)

# Filter out the files and keep only the directories
result <- result[file.info(result)$isdir]
result<-result[-1]
resultDF=c()
for(i in 1:length(result)){
  RealDistribution=readVDJcontigs(result[i])
  EMpredicted <- clonoStats(RealDistribution, method = 'EM')
  UNpredicted <- clonoStats(RealDistribution, method = 'unique')
  distance=getDistanceTwoSamples(clonoNames(UNpredicted),clonoAbundance(UNpredicted)[,1],clonoNames(EMpredicted),clonoAbundance(EMpredicted)[,1])
  resultDF[i]=distance
  print(i)
}
boxplot(resultDF)
hist(resultDF)
print(resultDF)
```